# config/jump_server.yaml
# Jump Server Configuration - Multi-Transport

servers:
  telnet:
    host: "0.0.0.0"
    port: 8023
    transport: "telnet"
    handler_class: "chuk_jump_server.handler:JumpPointTelnetHandler"
    max_connections: 100
    connection_timeout: 300
    welcome_message: "Welcome to the Jump Server"