# Auto-Detect Echo Server Configuration
# This server automatically detects whether clients are connecting
# via Telnet or WebSocket and handles them appropriately

# Common settings
host: 0.0.0.0
port: 8023
handler_class: sample_servers.echo_server:EchoTelnetHandler
transport: auto-detect

# WebSocket-specific settings
ws_path: /telnet
use_ssl: false
ssl_cert: ""
ssl_key: ""
allow_origins:
  - "*"
ping_interval: 30
ping_timeout: 10

# General server settings
max_connections: 100
connection_timeout: 300
welcome_message: "Welcome to the Auto-Detect Echo Server! This server automatically handles both Telnet and WebSocket clients."