# config/stock_server.yaml
# Stock Server Configuration - Multi-Transport

servers:
  telnet:
    host: "0.0.0.0"
    port: 8023
    transport: "telnet"
    handler_class: "sample_servers.stock_server:StockFeedHandler"
    max_connections: 100
    connection_timeout: 300
    welcome_message: "Welcome to the Stock Feed Server (Telnet)! Get real-time stock updates."

  tcp:
    host: "0.0.0.0"
    port: 8024
    transport: "tcp"
    handler_class: "sample_servers.stock_server:StockFeedHandler"
    max_connections: 100
    connection_timeout: 300
    welcome_message: "Welcome to the Stock Feed Server (TCP)! Get real-time stock updates."

  websocket:
    host: "0.0.0.0"
    port: 8025
    transport: "websocket"
    ws_path: "/stocks"
    handler_class: "sample_servers.stock_server:StockFeedHandler"
    use_ssl: false
    allow_origins:
      - "*"
    ping_interval: 30
    ping_timeout: 10
    max_connections: 100
    connection_timeout: 300
    welcome_message: "Welcome to the Stock Feed Server (WebSocket)! Get real-time stock updates."
  
  ws_telnet:
    host: "0.0.0.0"
    port: 8026
    transport: "ws_telnet"         # WebSocket over Telnet: performs Telnet negotiation over the WS transport
    ws_path: "/ws_telnet"
    handler_class: "sample_servers.echo_server:EchoWebSocketTelnetHandler"
    use_ssl: false
    ssl_cert: ""
    ssl_key: ""
    allow_origins:
      - "*"
    ping_interval: 30
    ping_timeout: 10
    max_connections: 100
    connection_timeout: 300
    welcome_message: "Welcome to the Stock Feed Server (WebSocket)! Get real-time stock updates."
